### ISSUE TITLE
Need an Object Mapper

### ISSUE THREAD

**Issue by nmondal** [nmondal/flower#1]
As it is very clear from the manifesto, we need to configuration based object mapping for most cases.
Those are non trivial language extensions.
A whole list is available from here:

https://www.npmjs.com/package/object-mapper

What would be a good one?
We do not know.

**Comment by nmondal** [comment]
After a long thinking process conclusion is we  should go with JXPath.
We can build amazingly powerful mapper using Xpath and functional mapping combined.

**Comment by BenitoJD** [comment]
May I know what made you come to the conclusion of using XPath?

**Comment by nmondal** [comment]
XPath is a standard.
https://www.w3.org/TR/1999/REC-xpath-19991116/
It is the same conclusion as "code is bad" and configuration works pretty well.
https://commons.apache.org/proper/commons-jxpath/

**Comment by nmondal** [comment]
Ok, so we do have a fully functional Object mapper as of now.
Here is the manual.
https://github.com/nmondal/flower/blob/master/ObjectMapper.md
Here is the integration manual:
https://github.com/nmondal/flower/blob/master/README.md#object-mapper

**Comment by nmondal** [comment]
Given things are in place - this gets closed.
